### ISSUE TITLE
Support for NextJS

### ISSUE THREAD

**Issue by nip10** [Vectopus/Atlas-icons-react#1]
I'm having a hard time trying to import an icon in a nextjs app using this library.

```bash
info  - Creating an optimized production build
Failed to compile.

./node_modules/@vectopus/atlas-icons-react/index.js
Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.
See https://webpack.js.org/concepts#loaders
> import _extends from '@babel/runtime/helpers/extends';
| import * as React from 'react';
|

Import trace for requested module:
./node_modules/@vectopus/atlas-icons-react/index.js
./components/UserCategoryManagement.tsx

> Build failed because of webpack errors
error Command failed with exit code 1.
```

Repro:
Just import any icon and try to build the app.

Env:
Next.js v13.0.7
Node v18.12.1

Not related but also consider adding support for TS so users don't have to create a .d.ts file.

Thanks for these amazing icons!

**Comment by mosamy19** [comment]
Hi @nip10, We are sorry for the Inconvenience. We added @types and I tested the new version on Next.js.
Could you please update Atlas-icons-react to the latest version?
