### ISSUE TITLE
React package does not include all the icons?

### ISSUE THREAD

**Issue by lmartins** [Vectopus/Atlas-icons-react#2]
I've trying to use the React library and it looks like this package may not include all the icons from the parent library. Is this accurate?

One example happens when trying to utilize one of the download icons by first importing it:
```js
import { NavigationMoveMovementArrowDirectionPointerNavigateDownDownload } from '@vectopus/atlas-icons-react';
```
Then add it to the render function:

```js
<NavigationMoveMovementArrowDirectionPointerNavigateDownDownload size={24} />
```

This results in the following error:
**Attempted import error: 'NavigationMoveMovementArrowDirectionPointerNavigateDownDownload' is not exported from '@vectopus/atlas-icons-react'.**

**Comment by mosamy19** [comment]
Hi @lmartins, Thank you for reporting this issue. It is fixed now
