### ISSUE TITLE
Error when trying to add Icon to component

### ISSUE THREAD

**Issue by michaelsoriano** [Vectopus/Atlas-icons-react#3]
I am getting the error below when I save the file (transpiles Typescript): 

**_Field 'browser' doesn't contain a valid alias configuration_**

It seems like it's not finding a directory of some sort? 

```
Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/p009509B/Sharepoint/spfx-pweb-home/node_modules/@vectopus/atlas-icons-react/node_modules doesn't exist or is not a directory
      /Users/11221222/Sharepoint/spfx-pweb-home/node_modules/@vectopus/atlas-icons-react/lib doesn't exist or is not a directory
      /Users/11221222/Sharepoint/spfx-pweb-home/node_modules/@vectopus/node_modules doesn't exist or is not a directory
      /Users/11221222/Sharepoint/spfx-pweb-home/node_modules/@vectopus/lib doesn't exist or is not a directory
```

this is how the folder looks like in node_modules:

<img width="383" alt="image" src="https://user-images.githubusercontent.com/5881081/221291992-f6cfb62d-5642-4443-bc21-e072c8c94d4c.png">

I am using 

-  "react": "17.0.1"
-  "react-dom": "17.0.1"

I am not sure if I installed incorrectly or have configured something wrong. Please advise.

**Comment by mosamy19** [comment]
Hi @michaelsoriano, Thank you for reporting this issue. 
I think this is related to custom webpack config, Could you please share with me your webpack config?

**Comment by michaelsoriano** [comment]
Hi @mosamy19  - sorry for the late response. I had to research where the webpack config is - since this is not a regular React Project. Apparently it's getting generated dynamically (https://github.com/SharePoint/sp-dev-docs/issues/6280), which might be causing the issue. In addition, I'm not sure if I can edit the file that generates the webpack config. Thank you anyway.
