### ISSUE TITLE
Invalid DOM properties

### ISSUE THREAD

**Issue by FabienFrays** [Vectopus/Atlas-icons-react#4]
Hello,

Thank's for your wonderful package! 
We have been trying to use it in a fresh React app using Vite JS and we encountered the following error in the Chrome dev tool console. 

![image](https://user-images.githubusercontent.com/4698233/229904059-b0eff306-ad5a-4edc-ba8a-5f897fd5f160.png)

Do you have an idea how to fix it ?

Best regards

**Comment by mosamy19** [comment]
Hi @FabienFrays, Thank you for reporting this issue,
It's fixed now, please make sure to update `@vectopus/atlas-icons-react` to the latest version `"^0.0.9"`

Thank you
