### ISSUE TITLE
Typescript: Make the icons accept react props such as className

### ISSUE THREAD

**Issue by kevinsmouts** [Vectopus/Atlas-icons-react#5]
I'm having an issue making the icons work with a className attribute to change colors.

![image](https://user-images.githubusercontent.com/1415547/230058241-72397f94-0215-4f79-bd18-436be970f799.png)

Here's how tabler/icons had it implemented
```
import { FC, SVGAttributes } from 'react';

type TablerIconProps = Omit<SVGAttributes<SVGElement>, 'color' | 'stroke'> & {
  color?: SVGAttributes<SVGElement>['stroke'];
  size?: SVGAttributes<SVGElement>['width'];
  stroke?: SVGAttributes<SVGElement>['strokeWidth'];
}

type TablerIcon = FC<TablerIconProps>;
```

**Comment by mosamy19** [comment]
Hi @kevinsmouts.


Currently the icons props are 
```
type IconType = {
    color?: string;
    size?: number | string;  
    weight?: "thin" | "medium" | "bold"
}
```

`className` isn't a valid prop. I just added a `color` prop that accepts HEX and CSS color names.

Please make sure to update `@vectopus/atlas-icons-react` to the latest version `"^0.0.9"`

Thank you

**Comment by kevinsmouts** [comment]
Thank you for your answer .

Not being able to use css class in that context is very handicapping. Enclosing the icon in span tags to apply the class results in misalignment of the icon inline.

**Comment by mosamy19** [comment]
@kevinsmouts I just added `className` as a prop, please make sure to update `@vectopus/atlas-icons-react `to the latest version `"^0.0.10"`

```
type IconType = {
    color?: string;
    size?: number | string;  
    weight?: "thin" | "medium" | "bold"
    className?: string;
}
```
